name: CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build docker image
        uses: docker/build-push-action@v2
        with:
          tags: dotfiles:latest
          push: false
      - 
        name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: dotfiles:latest
          options: -v ${{ github.workspace }}:/home/root/dotfiles -e HOME=/home/root -w /home/root/dotfiles
          run: bash -c "./tests/setup_test.sh"